trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: build
  jobs:
  - job: build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: cicdcontainerRepo
        containerRegistry: 2c00d603-1760-4da9-945b-c24786e43f03
        tags: |
          $(Build.SourceBranchName)
          $(Build.BuildId)
          $(Build.SourceVersion)

- stage: deploy_app
  jobs:
  - job: deploy
    steps:
    - script:  echo Build Docker
